-- RITMO · Migración v3 — ejecutar COMPLETA en Supabase > SQL Editor > New query.
-- Requiere que migration-v2.sql ya se haya ejecutado. Idempotente.
-- Aporta: registro diario de agua y sueño (widget de bienestar en Hoy).
-- La app funciona sin ella (el cliente detecta la tabla ausente y guarda solo
-- en la sesión), pero sin la migración el agua/sueño no persisten en tu cuenta.

create table if not exists public.daily_wellness (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  log_date date not null default current_date,
  water_ml integer not null default 0 check (water_ml >= 0 and water_ml <= 10000),
  sleep_hours numeric check (sleep_hours between 0 and 14),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, log_date)
);

create index if not exists daily_wellness_user_date_idx on public.daily_wellness(user_id, log_date desc);

alter table public.daily_wellness enable row level security;

drop policy if exists "wellness_select_own" on public.daily_wellness;
drop policy if exists "wellness_insert_own" on public.daily_wellness;
drop policy if exists "wellness_update_own" on public.daily_wellness;
drop policy if exists "wellness_delete_own" on public.daily_wellness;
create policy "wellness_select_own" on public.daily_wellness for select to authenticated using ((select auth.uid()) = user_id);
create policy "wellness_insert_own" on public.daily_wellness for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "wellness_update_own" on public.daily_wellness for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "wellness_delete_own" on public.daily_wellness for delete to authenticated using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.daily_wellness to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- El reset atómico (migration-v2.sql) también debe limpiar esta tabla.
create or replace function public.reset_user_data()
returns public.profiles
language plpgsql
security definer set search_path = ''
as $$
declare
  result public.profiles;
begin
  if auth.uid() is null then
    raise exception 'No autenticado';
  end if;
  delete from public.weight_logs      where user_id = auth.uid();
  delete from public.exercise_sets    where user_id = auth.uid();
  delete from public.food_preferences where user_id = auth.uid();
  delete from public.grocery_items    where user_id = auth.uid();
  delete from public.excluded_meals   where user_id = auth.uid();
  delete from public.meal_completions where user_id = auth.uid();
  delete from public.daily_wellness   where user_id = auth.uid();
  update public.profiles set
    name = 'Usuario', sex = 'other', birth_date = null, height_cm = 170,
    current_weight_kg = 70, target_weight_kg = 70, goal = 'maintain',
    weighing_day = 0, activity_level = 'moderate',
    exercise_types = array['Gimnasio']::text[], training_days = 3,
    meal_count = 4,
    schedule = '{"Desayuno":"08:00","Media mañana":"11:00","Comida":"13:30","Merienda":"17:00","Cena":"21:00","Entreno":"19:00"}'::jsonb,
    onboarding_completed = false, updated_at = now()
  where id = auth.uid()
  returning * into result;
  return result;
end;
$$;

revoke all on function public.reset_user_data() from public, anon;
grant execute on function public.reset_user_data() to authenticated;
