-- RITMO · Migración v4 — ejecutar COMPLETA en Supabase > SQL Editor > New query.
-- Requiere que migration-v2.sql y migration-v3.sql ya se hayan ejecutado. Idempotente.
-- Aporta: registro manual de comidas (alimentos fuera del catálogo: congelados,
-- comida fuera de casa…), con sus macros a mano. Suman a los totales del día.
-- La app funciona sin ella (el cliente detecta la tabla ausente y guarda solo
-- en la sesión), pero sin la migración las entradas manuales no persisten.

create table if not exists public.manual_meals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_date date not null default current_date,
  name text not null check (char_length(trim(name)) between 1 and 120),
  calories numeric not null default 0 check (calories >= 0 and calories <= 10000),
  protein numeric not null default 0 check (protein >= 0 and protein <= 1000),
  carbs numeric not null default 0 check (carbs >= 0 and carbs <= 1000),
  fat numeric not null default 0 check (fat >= 0 and fat <= 1000),
  created_at timestamptz not null default now()
);

create index if not exists manual_meals_user_date_idx on public.manual_meals(user_id, entry_date desc);

alter table public.manual_meals enable row level security;

drop policy if exists "manual_meals_select_own" on public.manual_meals;
drop policy if exists "manual_meals_insert_own" on public.manual_meals;
drop policy if exists "manual_meals_delete_own" on public.manual_meals;
create policy "manual_meals_select_own" on public.manual_meals for select to authenticated using ((select auth.uid()) = user_id);
create policy "manual_meals_insert_own" on public.manual_meals for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "manual_meals_delete_own" on public.manual_meals for delete to authenticated using ((select auth.uid()) = user_id);

grant select, insert, delete on public.manual_meals to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- El reset atómico también debe limpiar esta tabla (mantiene lo de v2 y v3).
create or replace function public.reset_user_data()
returns public.profiles
language plpgsql
security definer set search_path = ''
as $$
declare
  result public.profiles;
begin
  if auth.uid() is null then
    raise exception 'No autenticado';
  end if;
  delete from public.weight_logs      where user_id = auth.uid();
  delete from public.exercise_sets    where user_id = auth.uid();
  delete from public.food_preferences where user_id = auth.uid();
  delete from public.grocery_items    where user_id = auth.uid();
  delete from public.excluded_meals   where user_id = auth.uid();
  delete from public.meal_completions where user_id = auth.uid();
  delete from public.daily_wellness   where user_id = auth.uid();
  delete from public.manual_meals     where user_id = auth.uid();
  update public.profiles set
    name = 'Usuario', sex = 'other', birth_date = null, height_cm = 170,
    current_weight_kg = 70, target_weight_kg = 70, goal = 'maintain',
    weighing_day = 0, activity_level = 'moderate',
    exercise_types = array['Gimnasio']::text[], training_days = 3,
    meal_count = 4,
    schedule = '{"Desayuno":"08:00","Media mañana":"11:00","Comida":"13:30","Merienda":"17:00","Cena":"21:00","Entreno":"19:00"}'::jsonb,
    onboarding_completed = false, updated_at = now()
  where id = auth.uid()
  returning * into result;
  return result;
end;
$$;

revoke all on function public.reset_user_data() from public, anon;
grant execute on function public.reset_user_data() to authenticated;
