-- RITMO · Migración v5 — ejecutar COMPLETA en Supabase > SQL Editor > New query.
-- Requiere v2, v3 y v4. Idempotente.
-- Aporta: suscripciones de notificaciones push (recordatorio de pesaje semanal).
-- La función serverless de Vercel (/api/send-reminders) lee esta tabla con la
-- service role key y envía los avisos. El cliente guarda/borra su suscripción.

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  last_reminded_on date,
  created_at timestamptz not null default now(),
  unique (endpoint)
);

create index if not exists push_subscriptions_user_idx on public.push_subscriptions(user_id);

alter table public.push_subscriptions enable row level security;

drop policy if exists "push_select_own" on public.push_subscriptions;
drop policy if exists "push_insert_own" on public.push_subscriptions;
drop policy if exists "push_update_own" on public.push_subscriptions;
drop policy if exists "push_delete_own" on public.push_subscriptions;
create policy "push_select_own" on public.push_subscriptions for select to authenticated using ((select auth.uid()) = user_id);
create policy "push_insert_own" on public.push_subscriptions for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "push_update_own" on public.push_subscriptions for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "push_delete_own" on public.push_subscriptions for delete to authenticated using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.push_subscriptions to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- El reset atómico también debe limpiar esta tabla (mantiene v2, v3 y v4).
create or replace function public.reset_user_data()
returns public.profiles
language plpgsql
security definer set search_path = ''
as $$
declare
  result public.profiles;
begin
  if auth.uid() is null then
    raise exception 'No autenticado';
  end if;
  delete from public.weight_logs        where user_id = auth.uid();
  delete from public.exercise_sets      where user_id = auth.uid();
  delete from public.food_preferences   where user_id = auth.uid();
  delete from public.grocery_items      where user_id = auth.uid();
  delete from public.excluded_meals     where user_id = auth.uid();
  delete from public.meal_completions   where user_id = auth.uid();
  delete from public.daily_wellness     where user_id = auth.uid();
  delete from public.manual_meals       where user_id = auth.uid();
  delete from public.push_subscriptions where user_id = auth.uid();
  update public.profiles set
    name = 'Usuario', sex = 'other', birth_date = null, height_cm = 170,
    current_weight_kg = 70, target_weight_kg = 70, goal = 'maintain',
    weighing_day = 0, activity_level = 'moderate',
    exercise_types = array['Gimnasio']::text[], training_days = 3,
    meal_count = 4,
    schedule = '{"Desayuno":"08:00","Media mañana":"11:00","Comida":"13:30","Merienda":"17:00","Cena":"21:00","Entreno":"19:00"}'::jsonb,
    onboarding_completed = false, updated_at = now()
  where id = auth.uid()
  returning * into result;
  return result;
end;
$$;

revoke all on function public.reset_user_data() from public, anon;
grant execute on function public.reset_user_data() to authenticated;
