-- RITMO · Esquema inicial de Supabase
-- Ejecuta todo este archivo en Supabase > SQL Editor > New query.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default 'Usuario',
  sex text not null default 'other' check (sex in ('male','female','other')),
  birth_date date,
  height_cm numeric not null default 170 check (height_cm between 120 and 230),
  current_weight_kg numeric not null default 70 check (current_weight_kg between 35 and 300),
  target_weight_kg numeric not null default 70 check (target_weight_kg between 35 and 300),
  goal text not null default 'maintain' check (goal in ('lose','maintain','gain')),
  weighing_day smallint not null default 0 check (weighing_day between 0 and 6),
  activity_level text not null default 'moderate' check (activity_level in ('sedentary','light','moderate','high')),
  exercise_types text[] not null default array['Gimnasio']::text[],
  training_days smallint not null default 3 check (training_days between 0 and 7),
  meal_count smallint not null default 4 check (meal_count between 3 and 5),
  onboarding_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.food_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  food_name text not null check (char_length(trim(food_name)) between 1 and 100),
  restriction_type text not null check (restriction_type in ('blocked','allergy','disliked','favorite')),
  created_at timestamptz not null default now(),
  unique (user_id, food_name, restriction_type)
);

create table if not exists public.weight_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  weight_kg numeric not null check (weight_kg between 35 and 300),
  measured_at date not null default current_date,
  created_at timestamptz not null default now(),
  unique (user_id, measured_at)
);

create table if not exists public.grocery_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  week_start date not null,
  category text not null,
  name text not null,
  amount text not null,
  checked boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_id, week_start, name)
);

create table if not exists public.exercise_sets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  workout_name text not null,
  exercise_name text not null,
  set_number smallint not null check (set_number between 1 and 20),
  weight_kg numeric,
  repetitions smallint,
  performed_at timestamptz not null default now()
);

create index if not exists food_preferences_user_idx on public.food_preferences(user_id);
create index if not exists weight_logs_user_date_idx on public.weight_logs(user_id, measured_at desc);
create index if not exists grocery_items_user_week_idx on public.grocery_items(user_id, week_start);
create index if not exists exercise_sets_user_date_idx on public.exercise_sets(user_id, performed_at desc);

alter table public.profiles enable row level security;
alter table public.food_preferences enable row level security;
alter table public.weight_logs enable row level security;
alter table public.grocery_items enable row level security;
alter table public.exercise_sets enable row level security;

-- Se recrean las políticas para que el script pueda ejecutarse de nuevo.
drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select to authenticated using ((select auth.uid()) = id);
create policy "profiles_insert_own" on public.profiles for insert to authenticated with check ((select auth.uid()) = id);
create policy "profiles_update_own" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

drop policy if exists "food_select_own" on public.food_preferences;
drop policy if exists "food_insert_own" on public.food_preferences;
drop policy if exists "food_update_own" on public.food_preferences;
drop policy if exists "food_delete_own" on public.food_preferences;
create policy "food_select_own" on public.food_preferences for select to authenticated using ((select auth.uid()) = user_id);
create policy "food_insert_own" on public.food_preferences for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "food_update_own" on public.food_preferences for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "food_delete_own" on public.food_preferences for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "weight_select_own" on public.weight_logs;
drop policy if exists "weight_insert_own" on public.weight_logs;
drop policy if exists "weight_update_own" on public.weight_logs;
drop policy if exists "weight_delete_own" on public.weight_logs;
create policy "weight_select_own" on public.weight_logs for select to authenticated using ((select auth.uid()) = user_id);
create policy "weight_insert_own" on public.weight_logs for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "weight_update_own" on public.weight_logs for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "weight_delete_own" on public.weight_logs for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "grocery_select_own" on public.grocery_items;
drop policy if exists "grocery_insert_own" on public.grocery_items;
drop policy if exists "grocery_update_own" on public.grocery_items;
drop policy if exists "grocery_delete_own" on public.grocery_items;
create policy "grocery_select_own" on public.grocery_items for select to authenticated using ((select auth.uid()) = user_id);
create policy "grocery_insert_own" on public.grocery_items for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "grocery_update_own" on public.grocery_items for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "grocery_delete_own" on public.grocery_items for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "sets_select_own" on public.exercise_sets;
drop policy if exists "sets_insert_own" on public.exercise_sets;
drop policy if exists "sets_update_own" on public.exercise_sets;
drop policy if exists "sets_delete_own" on public.exercise_sets;
create policy "sets_select_own" on public.exercise_sets for select to authenticated using ((select auth.uid()) = user_id);
create policy "sets_insert_own" on public.exercise_sets for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "sets_update_own" on public.exercise_sets for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "sets_delete_own" on public.exercise_sets for delete to authenticated using ((select auth.uid()) = user_id);

-- Perfil base automático al registrar una cuenta.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'name', 'Usuario'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.food_preferences to authenticated;
grant select, insert, update, delete on public.weight_logs to authenticated;
grant select, insert, update, delete on public.grocery_items to authenticated;
grant select, insert, update, delete on public.exercise_sets to authenticated;
grant usage, select on all sequences in schema public to authenticated;
